# Automated Windows (MSVC++) testing using appveyor.com
# https://ci.appveyor.com/projects

version: 1.0.{build}

branches:
  only:
  - master

platform:
  - x86
  - x64

configuration:
  - Debug

before_build:
  "\"C:\\Program Files\\Microsoft SDKs\\Windows\\v7.1\\Bin\\SetEnv.cmd\" /%platform%"

build_script:
  - cl /nologo /W3 /WX /O2 /EHsc /DLIBDIVIDE_USE_SSE2=1 libdivide_test.cpp
  - cl /nologo /W3 /WX /O2 /EHsc /DLIBDIVIDE_USE_SSE2=1 primes_benchmark.cpp

test_script:
  - libdivide_test.exe
  - primes_benchmark.exe
